@startuml latierraMedia

Interface Arma {
  poder()
}

class Baculo{
  poder 
  poder()
}

class Espada {
    multiplicadorDePoder
    poderPorOrigen

    multiplicadorDePoder(unPoder) 
    multiplicadorDePoder()
    poderPorOrigen()
    poder()
}

class EspadaElfica {
    poderPorOrigen
}
  
class EspadaEnana {
    poderPorOrigen
}

class EspadaHumana {
    poderPorOrigen
}

class Daga {
    poder() 
    poderPorOrigen(unPoder) 
}

class Arco {
  tension  
  largo 
  
  largo() 
  poder() 
}

class Hacha  {
  largoDelMango 
  pesoDeHoja 

  largoDelMango() 
  pesoDeHoja() 
  poder()
}

abstract class Guerrero{
    cantidadDeVida 
    armas 
    items 
    armas() 
    poderArmas()
    cantidadDeVida(unaCantidad)
    obtenerPoder(unaCantidad)
    poder()
    cantidadDeVida()
    eliminarUnArma(unArma)
    vaciarArmas()
    perderVida(unaCantidad)
    aumentarVida(unaCantidad)
    tieneArmas()
    atravesar(unaZona)
    puedePasar(unaZona)
}

class Hobbit  {
  cantidadDeItems() 
  poder() 
}

class Enano  {
    factorDePoder 
    poder() 
}

class Elfo  {
    destrezaPropia 
    destrezaBase 
    sumarDestreza(unValor) 
    poder() 
}

class Humano  {
    limitadorDePoder 
    poder() 
}

class Maiar {
  poderBasico
  poderBajoAmenaza
  factorActual
  
  estaBajoAmenaza() 
  poder() 
}

object gollum {
  poder() 
}

object tom{
    vestimenta 
    poder()
    puedePasar(unaZona) 
    atravesar(unaZona) 
    vestimenta() 
}

class RequerimientoDeItem{
    item
    cantidad

    loCumplen(guerreros)
    obtenerCantidadItemsTotal(nombreItem, guerreros)
}

class RequerimientoDeGuerrero{
    condicion

    cumplenRequerimientoDePoder(guerreros)
    cumplenRequerimientoDeArmas(guerreros)
    loCumplen(guerreros)
}

class Zona {
    requerimiento 

    puedenPasar(guerreros)
}


class Camino{
    camino 
 
    dejarPasar(guerreros)
}

Interface AtravesarZona {
    puedePasar(unaZona) 
    atravesar(unaZona) 
}


Interface Requerimiento {
    loCumplen(guerrero)
}

Baculo .|> Arma
Espada .|> Arma
EspadaElfica --|> Espada
EspadaEnana --|> Espada
EspadaHumana --|> Espada
Daga --|> Espada
Arco .|> Arma
Hacha .|> Arma

Hobbit --|> Guerrero
Enano --|> Guerrero
Elfo --|> Guerrero
Humano --|> Guerrero
Maiar --|> Guerrero
gollum --|> Hobbit

tom .|> AtravesarZona
Guerrero .|> AtravesarZona

RequerimientoDeGuerrero .|> Requerimiento
RequerimientoDeItem .|> Requerimiento
Requerimiento --> Zona
Zona --> Camino
Arma --> Guerrero

Camino .> Guerrero


@enduml